### ISSUE TITLE
Cargar ficheros en MongoDB - MongoLab

### ISSUE THREAD

**Issue by sheilapbi** [Croqueta-OPS/proyecto-pintxopote#12]

**Comment by zmwebdev** [comment]
http://mongodb.github.io/node-mongodb-native/api-articles/nodekoarticle2.html

**Comment by sheilapbi** [comment]
Si, encontré eso para guardar ficheros pero creo que la otra manera es mas sencilla y ocupa menos espacio. Cuando vaya a implementarlo veré con cual me quedo.

**Comment by sheilapbi** [comment]
Solucionado con las imagenes en base64
