### ISSUE TITLE
Conseguido a 24/10/2014

### ISSUE THREAD

**Issue by borjamunoz** [Croqueta-OPS/proyecto-pintxopote#3]
-Prueba de login realizada, falta integrar en el proyecto.
-Instalación de ejs en el proyecto.

Puntos a realizar:
-Acceso de administrador: Gestión de pintxos y bares.
-Acceso de usuario registrado: Posibilidad de votar y comentar.
-Sección Pintxos: mostrar una imagen correspondiente por cada pintxo.
-Sección Rutas: mostrar rutas creadas por administradores. Google maps.

---------------------------------------------
-Sección bares: Guardar bares en bbdd y mostrar en la sección (2 ev.)

**Comment by sheilapbi** [comment]
:+1:
