### ISSUE TITLE
Despliegue OpenShift

### ISSUE THREAD

**Issue by Artzai** [Croqueta-OPS/proyecto-pintxopote#5]
The Pintxopo en OpenShift: http://pintxopoproject-pintxopoproject.rhcloud.com/

Para que funcione, he tenido que definir tres servidores al final de server.js

Al hacer un push a openshift master, hay que dejar descomentado solo el server de OpenShift (ya buscaré como hacerlo sin tener que andar cambiando servers).

**Comment by sheilapbi** [comment]
:ok:
