### ISSUE TITLE
cloud9 + OpenShift

### ISSUE THREAD

**Issue by Artzai** [Croqueta-OPS/proyecto-pintxopote#6]
Tambien he estado probando cloud9 (https://c9.io). 

cloud9 es un IDE, muy parecido a eclipse por lo que he podido ver, con coloreado y autocompletación o como se diga. Pero lo mejor es que tiene consola integrada y debugger con breakpoints! El debugger no me he puesto a mirarlo pero tiene buena pinta.

Tambien he conseguido conectar cloud9 con OpenShift y git, de modo que se puede desarrollar en cloud9, y desde el mismo IDE hacer push a origin master o a openshift master.

De este modo nos olvidamos de hacer nada en local, más que hacer pull de vez en cuando para tener copia del código en local.

Hacer el setup de todo esto es un poco rollo pero ya lo haré en clase también para verlo.

Como lo veis?

**Comment by sheilapbi** [comment]
:two_men_holding_hands:
