### ISSUE TITLE
No deja cargar pintxos en /profile

### ISSUE THREAD

**Issue by borjamunoz** [Croqueta-OPS/proyecto-pintxopote#9]
El problema es el siguiente, en Routes /profile, cuando intento hacer: 
     Pintxo.find(function(err, pintxos) {
	 	if (err) return console.error(err);
  		res.send(pintxos);
  		console.log(pintxos);
     });
Al haber ya 
         res.render('profile.ejs', {
			user : req.user
		});
Al intentar hacer un res.send y después un res.render se crea un conflicto y no carga nada. 
Lo que quiero es cargar un array con el find y luego con Ajax devolver ese contenido formateado a un <div> de profile.ejs

**Comment by sheilapbi** [comment]
Solved :white_check_mark:
